<a href="https://colab.research.google.com/github/quang-design/learnpytorch.io/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
x = torch.randn(7, 7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
y = torch.randn(1, 7)
# Perform matrix multiplication
x @ y.T

tensor([[-4.7411],
        [-1.9684],
        [-1.2816],
        [-0.2534],
        [ 2.1616],
        [ 3.3153],
        [-1.2443]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.randn(7, 7)
y = torch.randn(1, 7)
# Matrix multiply tensors
x @ y.T

tensor([[ 3.5168],
        [ 2.1984],
        [-1.7815],
        [ 3.8600],
        [-1.5010],
        [-1.6916],
        [-2.9352]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
tensor_A = torch.randn((2, 3), device=device)
tensor_B = torch.randn((2, 3), device=device)

print(tensor_A)
print(tensor_B)

Device: cuda
tensor([[-1.6165,  0.5685, -0.5102],
        [-0.9113, -1.1555, -0.2262]], device='cuda:0')
tensor([[ 0.6331,  1.6358, -0.3459],
        [ 1.0196, -0.4122,  1.4279]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
A_matmul_B = tensor_A @ tensor_B.T
A_matmul_B

tensor([[ 0.0830, -2.6109],
        [-2.3890, -0.7758]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [18]:
# Find max
print(A_matmul_B.max())
# Find min
print(A_matmul_B.min())

tensor(0.0830, device='cuda:0')
tensor(-2.6109, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [19]:
# Find arg max
print(A_matmul_B.argmax())

# Find arg min
print(A_matmul_B.argmin())

tensor(0, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [20]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_C = torch.randn(1, 1, 1, 10)

# Remove single dimensions
tensor_C_squeezed = torch.squeeze(tensor_C)

# Print out tensors and their shapes
print(tensor_C, tensor_C.shape)
print(tensor_C_squeezed, tensor_C_squeezed.shape)

tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]]) torch.Size([1, 1, 1, 10])
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822]) torch.Size([10])
